name: demo_dsc_test
description: A new Flutter application.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  url_launcher: ^5.5.3
  flutter_spinkit: ^4.1.2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - Images/

  fonts:
    - family: openSans
      fonts:
        - asset: openSans/OpenSans-Regular.ttf

    - family: varela
      fonts:
        - asset: Varela/VarelaRound-Regular.ttf

